baseURL = 'https://kouosi.netlify.app/'
languageCode = 'en-us'
title = 'Inogen Limbu'
enableRobotsTXT = true

[params]
    defaultDescription = "Welcome to my website."
    favicon = "/favicon.ico"

[permalinks]
    posts = '/posts/:title/'

[sitemap]
    changefreq = 'hourly'
    filename = 'sitemap.xml'
    priority = 0.5

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'monokai'
        tabWidth = 4

    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2
